version: '3'
services:
  db:
    image: postgres
    volumes:
      - pstgs_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
  web:
    image: diveintohacking/docker-compose-rails-6:0.0.4
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - cache:/cache
    environment:
      - BUNDLE_PATH=/app/vendor/bundle
      - SPROCKETS_CACHE=/cache
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  pstgs_db:
  cache:
